name: TriangleTest

on:
  push:
  pull_request:
    
jobs:
  run-triangle-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-versions:
          - "3.10"
          - "3.11"
    

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }} 

      - name: Install dependencies
        run: python -m pip install pytest .
      
      - name: Run Triangle test
        run: pytest